/**:
    ros__parameters:
        image_transport: raw    # image format
        size: 0.162             # default size

        # see "apriltag.h" 'struct apriltag_detector' for more documentation on these optional parameters
        detector:
            threads: 1          # number of threads
            decimate: 2.0       # decimate resolution for quad detection
            blur: 0.0           # sigma of Gaussian blur for quad detection
            refine: True        # snap to strong gradients
            sharpening: 0.25    # sharpening of decoded images
            debug: False        # write additional debugging images to current working directory

        pose_estimation_method: "pnp"   # method for estimating the tag pose

        # list of tags with their specific families
        tag:
            ids: [2, 1]                           
            families: ["Custom48h12","36h11"]    
            frames: ["tag_48", "tag_36"]          
            sizes: [0.6, 0.16]                    

        platform:
            enable: true
            frame_id: "platform"
            tag_ids: [2, 1]                       # Reference existing tags
            tag_x: [0.0, 0.0]                     # X positions
            tag_y: [0.0, 0.0]                     # Y positions
            tag_z: [0.0, 0.0]                     # Z positions 
